project_id: '562615'
api_token: '$CROWDIN_PERSONAL_TOKEN'
preserve_hierarchy: true
files:
  - source: /docs/**/*
    translation: /i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%
